#数据库配置
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure  # 为了某些版本的springboot  @SpringBootApplication(exclude= {DataSourceAutoConfiguration.class}) 无法生效
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master，如果只是单数据源只需要注释掉slave相关配置即可
      datasource:
        master:
          url: jdbc:oracle:thin:@xxxxxxx:1521:ORCL
          username: ipp
          password: password
          driverClassName: oracle.jdbc.OracleDriver
        #多数据源使用场景，如果需要更新工业运行监测数据，请增加名为“gyjc”的从数据源并配置链接
        #然后再做更新操作
        #若无需更新对应数据只需要配置主数据库为ipp主库账号密码即可
        gyjc:
          url: jdbc:oracle:thin:@xxxxxxxxxxxxx:1521:ORCL
          username: gyjcbi
          password: password
          driverClassName: oracle.jdbc.OracleDriver
        safe:
          url: jdbc:oracle:thin:@xxxxxxxxxx:1521:ORCL
          username: safe
          password: password
          driverClassName: oracle.jdbc.OracleDriver
        #slave:
          #url: jdbc:oracle:thin:@localhost:1521:ORCL
          #username: ipp
          #password: password
          #driverClassName: oracle.jdbc.driver.OracleDriver
        #安全态势感知数据库
        #secure:
          #url: jdbc:oracle:thin:@xxxxxxxxxxxx:1521:ORCL
          #username: secure
          #password: password
          #driverClassName: oracle.jdbc.OracleDriver
      #validation-query: SELECT 1
      druid:
        wall:
          multi-statement-allow: true
        initial-size: 10
        max-active: 100
        pool-prepared-statements: true #打开PSCache
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          log-slow-sql: true #打印慢sql
          slow-sql-millis: 10000 #慢sql时间,超过10秒打印
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
  #上传文件大小设置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

#mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.thinvent.entity
  check-config-location: true
  configuration:
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning
    #查询为空时保持key
    return-instance-for-empty-row: true
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: UUID
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 0
      #逻辑未删除值
      logic-not-delete-value: 1
  type-handlers-package: com.thinvent.handler

server:
  port: 8090

logging:
  level:
    com: INFO


# api url
requestApi:
  #url: http://xxxxxxxxxxxxx
  url: http://xxxxxxxxxxxxxxxxxxx